version: "3.3"
   
services:
    django:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: django
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        depends_on:
            - redis
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
