# Generated by Django 3.1.2 on 2023-08-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0141_auto_20230807_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='designation',
            field=models.CharField(choices=[('0', 'Jr. Assistant'), ('1', 'Jr. Superintendent'), ('2', 'Jr. Technical Superintendent'), ('3', 'Jr. Technician'), ('4', 'Technical Superintendent'), ('5', 'Sr. Assistant'), ('6', 'Sr. Superintendent'), ('7', 'Sr. Technical Superintendent'), ('8', 'Sr. Technician'), ('9', 'Technical Officer Gr I'), ('10', 'Technical Officer Gr II'), ('11', 'Junior Technical Officer'), ('12', 'Asst. Workshop Superintendent'), ('12.5', 'Workshop Superintendent'), ('13', 'Senior Technical Officer'), ('15', 'PostDoc'), ('16', 'Others')], default='15', max_length=4),
        ),
    ]
