# Generated by Django 3.1.2 on 2024-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0143_auto_20230807_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='body',
        ),
        migrations.RemoveField(
            model_name='student',
            name='co_supervisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_exchange',
        ),
        migrations.RemoveField(
            model_name='student',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='thesis_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='website',
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
