# Generated by Django 3.1.2 on 2024-03-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0144_auto_20240316_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatch',
            name='csv_file_hash',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
