# Generated by Django 3.1.2 on 2024-03-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0145_studentbatch_csv_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatch',
            name='csv_file_hash',
        ),
    ]
