# Generated by Django 3.1.2 on 2024-03-26 16:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0146_remove_studentbatch_csv_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervisor', to='mechweb.facultypage', verbose_name='Co-supervisor'),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_address',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='student',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='International Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='mechweb.facultypage', verbose_name='Main supervisor/Faculty Advisor'),
        ),
        migrations.AddField(
            model_name='student',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
