# Generated by Django 3.1.2 on 2024-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechweb', '0148_auto_20240326_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_address',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
